name = "arb-desk"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "arb-desk-db"
database_id = "5067943f-6a75-4f58-afbd-b311fb2aab39"